In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt


In [43]:
data=pd.read_csv('E:\\ALL AI\\dataset\\Salary_Data.csv')
data.head()
data.shape
from sklearn.preprocessing import StandardScaler
std=StandardScaler()
data=std.fit_transform(data)
data=data.T
data

array([[-1.51005294, -1.43837321, -1.36669348, -1.18749416, -1.11581443,
        -0.86493538, -0.82909552, -0.75741579, -0.75741579, -0.57821647,
        -0.50653674, -0.47069688, -0.47069688, -0.43485702, -0.29149756,
        -0.1481381 , -0.07645838, -0.00477865,  0.21026054,  0.2461004 ,
         0.53281931,  0.6403389 ,  0.92705781,  1.03457741,  1.21377673,
         1.32129632,  1.50049564,  1.5363355 ,  1.78721455,  1.85889428],
       [-1.36011263, -1.10552744, -1.419919  , -1.20495739, -1.33978143,
        -0.71830716, -0.58815781, -0.79981746, -0.42881019, -0.69801306,
        -0.47433279, -0.74976858, -0.70662043, -0.70201994, -0.55250402,
        -0.29921736, -0.37004264,  0.26285865,  0.19885989,  0.66547573,
         0.58377993,  0.82623317,  0.93861127,  1.40274136,  1.24020308,
         1.09740238,  1.51986835,  1.3590738 ,  1.72102849,  1.70177321]])

In [35]:
x=data[0].reshape(-1,1)
y=data[1].reshape(-1,1)
x

array([[-1.51005294],
       [-1.43837321],
       [-1.36669348],
       [-1.18749416],
       [-1.11581443],
       [-0.86493538],
       [-0.82909552],
       [-0.75741579],
       [-0.75741579],
       [-0.57821647],
       [-0.50653674],
       [-0.47069688],
       [-0.47069688],
       [-0.43485702],
       [-0.29149756],
       [-0.1481381 ],
       [-0.07645838],
       [-0.00477865],
       [ 0.21026054],
       [ 0.2461004 ],
       [ 0.53281931],
       [ 0.6403389 ],
       [ 0.92705781],
       [ 1.03457741],
       [ 1.21377673],
       [ 1.32129632],
       [ 1.50049564],
       [ 1.5363355 ],
       [ 1.78721455],
       [ 1.85889428]])

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.20,random_state=0)
len(xtrain)

24

In [33]:
len(xtest)

6

In [38]:
from sklearn.linear_model import LinearRegression
alg=LinearRegression()
alg.fit(xtrain,ytrain)


LinearRegression()

In [39]:
alg.coef_

array([[0.96401956]])

In [40]:
alg.intercept_

array([0.00956883])

In [41]:
y_pred=alg.predict(xtest)
y_pred

array([[-1.30795042],
       [ 1.73247863],
       [-0.40964184],
       [-0.4787425 ],
       [ 1.45607599],
       [ 1.17967335]])

In [42]:
ytest

array([[-1.419919  ],
       [ 1.72102849],
       [-0.70201994],
       [-0.47433279],
       [ 1.51986835],
       [ 1.24020308]])